chapter3課題
aishimakouki/furi_exercise pull request #3
Opened 2021-05-31 16:11 UTC by aishimakouki

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/03.md

### 課題番号
課題2
課題3

### 現在の状況
課題2
実行したとき、int(1) int(2) string(6) "アホ"・・・・出力され
1 2 アホ・・・と出力しない。

課題3
 条件3の3の倍数かつ 5 の倍数の時は FizzBuzzが出力されない。
実行したとき、int(1) int(2) string(4) "Fizz"と出力され
1 2 Fizz・・・と出力しない。

### 調べたこと・参考にしたURL
https://www.javadrive.jp/php/if/index6.html

2021-06-01 00:50 UTC, yukishimizumg commented
@aishimakouki 
`var_dump`は値のデータ型など変数の情報を表示するため、`int(1)`等が出力されています👍
文字列を出力する場合は[echo](https://www.php.net/manual/ja/function.echo.php)を使いましょう✨
コードとてもキレイです！！

2021-06-01 01:00 UTC, yukishimizumg commented
@aishimakouki 
課題3の「条件3の3の倍数かつ 5 の倍数の時は FizzBuzzが出力されない」件については、
3で割り切れる場合の条件を先に持ってきているため、
例えば`15`は`Fizz`が出力されます👍
最初の`if`文でに「3の倍数かつ 5 の倍数で割り切れる場合」の条件を設定してください✨

2021-06-01 13:53 UTC, aishimakouki commented
### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/03.md


### メッセージ
chapter3の課題すべて完了しました！
ご確認お願いします！

2021-06-01 21:59 UTC, kazu-taka requested changes
@aishimakouki 
いくつかコメントしたので確認お願いします:bow:

2021-06-01 21:59 UTC, kazu-taka commented on chap3_2.php
> +        echo($int = "アホ");
@aishimakouki 
`$int = "アホ"`だと、`$int`という変数に"アホ"という文字列を代入しているということになります！
アホと出力したい場合は、`echo`関数の後ろに、出力したい文字列を渡すだけでOKです👍

2021-06-01 21:59 UTC, kazu-taka commented on chap3_2.php
> +        echo($int);
@aishimakouki 
今の状態だと、`12アホ45`と文字がくっついて表示されてしまうので、カリキュラムのように、間にスペース１文字いれるようにお願いします✨

2021-06-01 21:59 UTC, kazu-taka commented on chap3_3.php
> +        echo ($int);
@aishimakouki 
細かくて申し訳ないですが、
`} elseif(`のifの後ろにはスペースを入れて
`} elseif (`にするようにお願いします！
また、`echo`関数で`()`を使用する場合は、公式ドキュメントに従って、`echo(XXXX)`とスペース無しで書くように統一お願いします✨
https://www.php.net/manual/ja/function.echo.php

2021-06-14 12:53 UTC, aishimakouki commented
## カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/03.md


### メッセージ
課題chap3_2.php,chap3_3.php を修正しました。
ご確認よろしくお願いします。

2021-06-14 13:44 UTC, kazu-taka requested changes
@aishimakouki 
2箇所見逃していた部分と、他1箇所修正お願いします✨

2021-06-14 13:44 UTC, kazu-taka commented on chap3_1.php
> +<?
@aishimakouki 
今気が付きましたが、PHPの開始タグは`<?php`になるので、全てのファイルの修正お願いします:bow:

2021-06-14 13:44 UTC, kazu-taka commented on chap3_2.php
> +        echo ($int. " ");
@aishimakouki 
修正してもらったタイミングで、`echo`の後ろにスペースが入ってしまったので削除お願いします✨

2021-06-14 13:44 UTC, kazu-taka commented on chap3_3.php
> +        echo("Fuzz". " ");
@aishimakouki 
`Fizz`じゃなくて`Fuzz`になってしまってました😆

2021-06-14 13:53 UTC, aishimakouki commented
カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/03.md

メッセージ
課題chap3_2.php,chap3_3.php を修正しました。
何度もすいません。
ご確認よろしくお願いします。

2021-06-14 18:57 UTC, kazu-taka commented on chap3_1.php
> +<?
@aishimakouki 
> @aishimakouki
> 今気が付きましたが、PHPの開始タグは`<?php`になるので、全てのファイルの修正お願いします🙇

こちらの件がまだ修正されていないようなので、修正お願いします:bow:

2021-06-14 18:58 UTC, kazu-taka commented
@aishimakouki 
> @aishimakouki
> 今気が付きましたが、PHPの開始タグは`<?php`になるので、全てのファイルの修正お願いします🙇

こちらの件がまだ修正されていないようなので、修正お願いします:bow:

2021-06-15 13:51 UTC, aishimakouki commented
何度もすいません。
ご指摘の件、修正しました。
ご確認よろしくお願いします。

2021-06-16 01:35 UTC, yukishimizumg reviewed
@aishimakouki 
細かいところだけになりますが、コメントしましたので確認お願いします😊🍀

2021-06-16 01:35 UTC, yukishimizumg commented on chap3_1.php
> +$blood_types = [ "A","B","O","AB" ];
細かいですが、`[の後ろ`と`]の前`のスペースを削除し、`,の後ろ`にスペースを入れてください🌼

```php
$blood_types = ["A", "B", "O", "AB"];
```

2021-06-16 01:35 UTC, yukishimizumg commented on chap3_1.php
> +foreach( $blood_types as $blood_type ){
`(の後ろ`と`)の前`のスペースを削除し、`foreachと(の間`と`)と{の間`にスペースを入れてください✨

```php
foreach ($blood_types as $blood_type) {
```

2021-06-16 01:35 UTC, yukishimizumg commented on chap3_1.php
> +    var_dump( $blood_type . "型です");
`(と$blood_typeの間`のスペース削除お願いします✨

```php
var_dump($blood_type . "型 です");
```

2021-06-16 01:35 UTC, yukishimizumg commented on chap3_2.php
> +        echo("アホ". " ");
`.`の前にスペース追加お願いします😊

※ echo は`()`なしでOKです(修正は不要です)✨

```php
echo "アホ" . " ";
```

2021-06-16 01:35 UTC, yukishimizumg commented on chap3_2.php
> +        echo($int. " ");
`.`の前にスペース追加お願いします😊

2021-06-16 01:35 UTC, yukishimizumg commented on chap3_3.php
> +        echo("FizzBuzz". " ");
`.`の前にスペース追加お願いします😊
以降の3箇所も同様に修正お願いします✨

```php
echo("FizzBuzz" . " ");

echo("Buzz" . " ");

echo("Fizz" . " ");

echo($int . " ");
```

2021-06-16 12:43 UTC, aishimakouki commented
再度修正しました。
ご確認よろしくお願いします。

2021-06-17 04:58 UTC, yukishimizumg commented
@aishimakouki 
修正ありがとうございます、コードとてもキレイです🌸🌸
OKでしたので、マージしてください✨
お疲れさまでした😊!!

![LGTM](https://image.lgtmoon.dev/113894)

2021-06-17 06:33 UTC, aishimakouki commented
ありがとうございます！

2021-06-17 06:33 UTC, merged